const STATIONS = {
  n1: { zona:'nac', nombre:'1. Aulas del Siglo XXI - Computadores para Educar',
    img:'https://images.unsplash.com/photo-1568658176307-e730ceea3576?w=800',
    contexto:'Escuelas públicas urbanas con brechas de equipamiento superadas en el territorio nacional.',
    enfoque:'Constructivismo social y alfabetización digital crítica.',
    metodologia:'Aprendizaje Basado en Proyectos (ABP) transdisciplinares.',
    tics:'Laboratorios virtuales, tabletas con software interactivo sin necesidad de conectividad permanente y kits de robótica educativa de bajo costo.',
    aportes:'Democratización del acceso tecnológico mediante contenidos regionales precargados para superar barreras de conectividad.' },
  n2: { zona:'nac', nombre:'2. Escuela Nueva Activa - Innovación Rural',
    img:'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800',
    contexto:'Aulas multigrado en zonas rurales dispersas de difícil acceso geográfico.',
    enfoque:'Aprendizaje centrado en el estudiante, cooperativo y adaptado a ritmos individuales de desarrollo.',
    metodologia:'Aprendizaje Cooperativo Adaptativo respaldado por guías de autoaprendizaje contextualizadas.',
    tics:'Plataformas móviles de seguimiento comunitario, recursos educativos digitales en audio (podcasts didácticos) y terminales con carga solar.',
    aportes:'Flexibilidad absoluta del calendario escolar para asimilar los ciclos agrícolas de la región sin penalizar la permanencia del estudiante.' },
  n3: { zona:'nac', nombre:'3. Ruta STEM+A - Tecnoacademias SENA',
    img:'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=800',
    contexto:'Educación media técnica formal articulada con centros avanzados de desarrollo tecnológico.',
    enfoque:'Enfoque STEM+A (Ciencia, Tecnología, Ingeniería, Matemáticas + Arte) orientado a la resolución de problemáticas del entorno real.',
    metodologia:'Aprendizaje Basado en Retos (ABR) apoyado en metodologías de Ingeniería de Diseño.',
    tics:'Modelado e impresión 3D, entornos virtuales de simulación de circuitos electrónicos, programación estructurada/bloques e IA para análisis de datos.',
    aportes:'Espacios de co-creación entre estudiantes de secundaria e investigadores técnicos para formular patentes y prototipos funcionales locales.' },
  n4: { zona:'nac', nombre:'4. Aulas en Paz - Convivencia Digital',
    img:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800',
    contexto:'Instituciones educativas vulnerables o afectadas por dinámicas complejas de convivencia social.',
    enfoque:'Educación socioemocional orientada al desarrollo sistemático de competencias ciudadanas críticas.',
    metodologia:'Juego de Roles (Role-playing) y debates guiados basados en dilemas morales auténticos de la cotidianidad.',
    tics:'Videojuegos serios (simuladores interactivos de toma de decisiones), narrativas transmedia y foros digitales de mediación escolar.',
    aportes:'Integración orgánica de la salud mental y la empatía dentro del currículo académico estándar usando métricas de seguimiento digital.' },
  n5: { zona:'nac', nombre:'5. Territorios Creativos - Computadores para Educar Innova',
    img:'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800',
    contexto:'Instituciones educativas de carácter étnico e intercultural en regiones de alta diversidad cultural.',
    enfoque:'Etnoeducación activa e interculturalidad crítica fundamentada.',
    metodologia:'Aprendizaje Basado en la Indagación coordinado con ejercicios de cartografía social comunitaria.',
    tics:'Herramientas digitales de traducción para lenguas nativas desarrolladas en clase, producción audiovisual para el rescate oral y sistemas de información geográfica (SIG).',
    aportes:'Fusión de saberes y tradiciones ancestrales con herramientas tecnológicas modernas para asegurar la preservación de la identidad.' },
  i1: { zona:'intl', nombre:'6. Modelo Fenómeno (Phenomenon-Based Learning) — Finlandia',
    img:'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800',
    contexto:'Sistema educativo nacional público descentralizado, enfocado en equidad social.',
    enfoque:'Aprendizaje holístico, integrado y profundamente contextualizado en la vida real.',
    metodologia:'Aprendizaje Basado en Fenómenos, suprimiendo las divisiones rígidas de las asignaturas tradicionales.',
    tics:'Entornos virtuales de aprendizaje integrados (LMS), aplicaciones de co-diseño digital y portafolios interactivos en la nube.',
    aportes:'Abordaje de problemáticas globales (v.g., cambio climático) movilizando simultáneamente conceptos de geografía, química, economía e historia.' },
  i2: { zona:'intl', nombre:'7. High Tech High — San Diego, Estados Unidos',
    img:'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800',
    contexto:'Red de escuelas públicas charter de alta diversidad, pionera en el diseño curricular alternativo.',
    enfoque:'"Deeper Learning": conocimiento aplicado con propósitos reales y transferencia al entorno público.',
    metodologia:'Aprendizaje Basado en Proyectos (ABP) de largo alcance que culminan obligatoriamente en exposiciones comunitarias.',
    tics:'Software de diseño arquitectónico y modelado CAD, herramientas colaborativas de gestión de proyectos (Trello, Asana) y suites multimedia.',
    aportes:'Sustitución de exámenes estandarizados por defensas públicas de portafolios ante expertos e infraestructura escolar de planta abierta.' },
  i3: { zona:'intl', nombre:'8. Movimiento Maker — Tinkering Studio (Exploratorium)',
    img:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    contexto:'Red global de espacios de aprendizaje no formal y laboratorios escolares de experimentación activa.',
    enfoque:'Construccionismo pedagógico puro enfocado en el aprendizaje mediante el diseño y el ensayo-error.',
    metodologia:'Tinkering (pensar con las manos) combinando arte, ciencia y tecnología lúdica.',
    tics:'Microcontroladores de hardware libre (Arduino, Makey Makey), sensores ambientales de código abierto y maquinaria de fabricación digital.',
    aportes:'Reencuadre del error escolar como un proceso iterativo normalizado, eliminando la frustración mediante el rediseño continuo.' },
  i4: { zona:'intl', nombre:'9. Aulas Inteligentes — Singapur (Smart Nation)',
    img:'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
    contexto:'Escuelas hiperconectadas de alto rendimiento técnico bajo la política institucional "Thinking Schools, Learning Nation".',
    enfoque:'Desarrollo sistemático del pensamiento computacional y habilidades metacognitivas superiores.',
    metodologia:'Resolución de problemas complejos estructurada sobre la progresión metodológica Concreto-Pictórico-Abstracto (CPA).',
    tics:'Tutores inteligentes basados en IA adaptativa, analíticas de aprendizaje masivas en tiempo real y entornos inmersivos de realidad aumentada.',
    aportes:'Plataformas adaptativas que modifican la complejidad del problema en tiempo real por estudiante, facilitando la intervención oportuna del maestro.' },
  i5: { zona:'intl', nombre:'10. Red Global de Aprendizaje (NPDL) — Michael Fullan',
    img:'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
    contexto:'Asociación internacional de centros escolares orientada a la transformación profunda de las prácticas de enseñanza.',
    enfoque:'Marco de las "6 Cs": Carácter, Ciudadanía, Colaboración, Comunicación, Creatividad y Pensamiento Crítico.',
    metodologia:'Aprendizaje Profundo (Deep Learning) catalizado por alianzas de impacto con el entorno social circundante.',
    tics:'Redes globales de comunicación escolar, plataformas para videoconferencias de co-diseño multinacional y rúbricas de evaluación en la nube.',
    aportes:'Evaluación sistémica del progreso educativo mediante un tejido de rúbricas interconectadas a nivel mundial en diversos continentes.' }
};

// Posiciones dentro de cada sala: [x, y, z, rotY, imgThumb, etiqueta corta]
const LAYOUT_NAC = {
  n1: [-14.8, 2.8, -12, 90,  'https://images.unsplash.com/photo-1568658176307-e730ceea3576?w=500', '1. Computadores para Educar'],
  n2: [-14.8, 2.8, -1,  90,  'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=500', '2. Escuela Nueva Activa'],
  n3: [-14.8, 2.8, 10,  90,  'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=500', '3. Ruta STEM+A SENA'],
  n4: [14.8,  2.8, -12, -90, 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500', '4. Aulas en Paz'],
  n5: [14.8,  2.8, -1,  -90, 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=500', '5. Territorios Creativos']
};
const LAYOUT_INTL = {
  i1: [-14.8, 2.8, -12, 90,  'https://images.unsplash.com/photo-1544717305-2782549b5136?w=500', '6. Modelo Finlandia'],
  i2: [-14.8, 2.8, -1,  90,  'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=500', '7. High Tech High'],
  i3: [-14.8, 2.8, 10,  90,  'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=500', '8. Movimiento Maker'],
  i4: [14.8,  2.8, -12, -90, 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500', '9. Metodo Singapur'],
  i5: [14.8,  2.8, -1,  -90, 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=500', '10. Red Global NPDL']
};
